In [14]:
from tensorflow.keras.preprocessing.text import one_hot

In [15]:
### sentences
sent=[  'the glass of milk',
      'the glass of juice',
      'the cup of tea',
    'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good',]

In [16]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [17]:
# Define the vocabulary size
voc_size=10000

In [18]:
# one hot representation for each word

one_hot_rep = [one_hot(words,voc_size) for words in sent]
one_hot_rep
    

[[8944, 2232, 7948, 1834],
 [8944, 2232, 7948, 6911],
 [8944, 2401, 7948, 7015],
 [8614, 1936, 2722, 3597, 905],
 [8614, 1936, 2722, 3597, 991],
 [6900, 8944, 3934, 7948, 7537],
 [979, 9478, 1416, 3597]]

In [20]:
# Word embedding representation
from tensorflow.keras.layers import Embedding # to convert the one hot representation into word embedding representation
from tensorflow.keras.utils import pad_sequences # to make the length of all the sentences same
from tensorflow.keras.models import Sequential


In [21]:
import numpy as np

In [25]:
set_len = 8 # to make the length of all the sentences same, we should keep more than the length of the longest sentence
embeded_docs = pad_sequences(one_hot_rep,padding='pre',maxlen=set_len) # pre means that the padding will be done at the beginning of the sentence, we can add post if we want to add the padding at the end of the sentence
print(embeded_docs)

[[   0    0    0    0 8944 2232 7948 1834]
 [   0    0    0    0 8944 2232 7948 6911]
 [   0    0    0    0 8944 2401 7948 7015]
 [   0    0    0 8614 1936 2722 3597  905]
 [   0    0    0 8614 1936 2722 3597  991]
 [   0    0    0 6900 8944 3934 7948 7537]
 [   0    0    0    0  979 9478 1416 3597]]


In [26]:
# feature representation using embedding
dim = 10 # dimension of the embedding vector, we can choose any value for this, but it should be less than the vocabulary size

In [28]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=set_len)) # voc_size is the vocabulary size, dim is the dimension of the embedding vector, input_length is the length of the input sequence
model.compile('adam','mse') # adam is the optimizer, mse is the loss function

In [29]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [31]:
model.predict(embeded_docs) # to get the feature representation of the sentences using embedding

1/1 [==============================] - 0s 41ms/step


array([[[ 0.00862258, -0.02848152,  0.0412153 , -0.03659087,
         -0.02023579, -0.04759229,  0.04098992, -0.00040466,
         -0.00673419, -0.04642889],
        [ 0.00862258, -0.02848152,  0.0412153 , -0.03659087,
         -0.02023579, -0.04759229,  0.04098992, -0.00040466,
         -0.00673419, -0.04642889],
        [ 0.00862258, -0.02848152,  0.0412153 , -0.03659087,
         -0.02023579, -0.04759229,  0.04098992, -0.00040466,
         -0.00673419, -0.04642889],
        [ 0.00862258, -0.02848152,  0.0412153 , -0.03659087,
         -0.02023579, -0.04759229,  0.04098992, -0.00040466,
         -0.00673419, -0.04642889],
        [ 0.00782444,  0.00541038,  0.02492828, -0.04449986,
          0.01461972,  0.02322589,  0.0119171 , -0.03744626,
          0.0271566 ,  0.00907608],
        [-0.01835351, -0.01733502, -0.04954619, -0.01402156,
         -0.03802526,  0.03003789, -0.01351691, -0.00446206,
         -0.00050972,  0.02031392],
        [ 0.01984272,  0.04923943,  0.00583043, -0.0

In [32]:
model.predict(embeded_docs).shape # to get the shape of the feature representation of the sentences using embedding

1/1 [==============================] - 0s 105ms/step


(7, 8, 10)

In [33]:
# we got (7, 8, 10) which means that we have 7 sentences, each sentence has 8 words and each word is represented by a 10 dimensional vector using embedding

In [34]:
embeded_docs[0] # to get the one hot representation of the first sentence

array([   0,    0,    0,    0, 8944, 2232, 7948, 1834])

In [36]:
model.predict(embeded_docs[0]) # to get the feature representation of the first sentence using embedding, we got (8, 10) which means that we have 8 words in the first sentence and each word is represented by a 10 dimensional vector using embedding 

1/1 [==============================] - 0s 47ms/step


array([[ 0.00862258, -0.02848152,  0.0412153 , -0.03659087, -0.02023579,
        -0.04759229,  0.04098992, -0.00040466, -0.00673419, -0.04642889],
       [ 0.00862258, -0.02848152,  0.0412153 , -0.03659087, -0.02023579,
        -0.04759229,  0.04098992, -0.00040466, -0.00673419, -0.04642889],
       [ 0.00862258, -0.02848152,  0.0412153 , -0.03659087, -0.02023579,
        -0.04759229,  0.04098992, -0.00040466, -0.00673419, -0.04642889],
       [ 0.00862258, -0.02848152,  0.0412153 , -0.03659087, -0.02023579,
        -0.04759229,  0.04098992, -0.00040466, -0.00673419, -0.04642889],
       [ 0.00782444,  0.00541038,  0.02492828, -0.04449986,  0.01461972,
         0.02322589,  0.0119171 , -0.03744626,  0.0271566 ,  0.00907608],
       [-0.01835351, -0.01733502, -0.04954619, -0.01402156, -0.03802526,
         0.03003789, -0.01351691, -0.00446206, -0.00050972,  0.02031392],
       [ 0.01984272,  0.04923943,  0.00583043, -0.03852696,  0.03782702,
        -0.00811957,  0.0007874 , -0.04851839